### PR TITLE
Callback for clicking on annotations #76

### PR DESCRIPTION
**Pull request by t29mato**
to support the callback function on annotation for #76 

## behavior

https://github.com/user-attachments/assets/becbc6d7-eeed-4eca-b3fc-8f8cfd0b3aab

I've tested using the application structure-vision https://github.com/lfoppiano/structure-vision/pull/4

### CODE REVIEW

**Comment by t29mato** [comment]
The ci error comes from my code? ...

**Comment by t29mato** [comment]
https://github.com/lfoppiano/streamlit-pdf-viewer/actions/runs/12107866260
The test was working before on the main branch. 
So, I'm going to figure it out by myself first.

**Comment by t29mato** [comment]
@lfoppiano 
The tests passed in the local Python 3.11 environment.
image

Considering this, I’m beginning to think that it might be necessary to set up local environments for Python 3.7 and Python 3.8, where the tests have been failing so far.

However, looking at the specific error details in the GitHub Actions logs, as shown below, the test might be unstable since I haven’t made any changes to the code that would affect the height or the number of components.

https://github.com/lfoppiano/streamlit-pdf-viewer/actions/runs/12139594120/job/33847552805?pr=80
```python
>       assert round(b_box_1['height']) < iframe_box['height'] and round(b_box_1['height']) > 0
E       assert (2378 < 926.9999694824219)
E        +  where 2378 = round(2377.7000427246094)

tests/test_tabs.py:86: AssertionError
```

https://github.com/lfoppiano/streamlit-pdf-viewer/actions/runs/12139709855/job/33847907010?pr=80
```python
>       assert len(iframe_components) == 6
E       assert 5 == 6
E        +  where 5 = len([<Locator frame=<Frame name= url='http://localhost:40857/'> selector='iframe[title="streamlit_pdf_viewer.streamlit_pdf...me name= url='http://localhost:40857/'> selector='iframe[title="streamlit_pdf_viewer.streamlit_pdf_viewer"] >> nth=4'>])

tests/test_resolution_boost.py:42: AssertionError
```


Could you share your thoughts before I investigate further?

**Comment by Krastanov** [comment]
This works great locally for me (python 3.10)

**Comment by lfoppiano** [comment]
Thanks for this PR, it's great you've done it. I tried myself but I failed... I really appreciate. 
Regarding the tests, they are not 100% accurate, but we need them for avoiding pushing stupid bugs. Maybe we would need to update them. I will look into them.

**Comment by lfoppiano** [comment]
It seems tests work. 

Could you please add some documentation in the readme.md?

**Comment by lfoppiano** [comment]
I found that the tests are running with the 3.10.12 version no matter what we set up before... no idea why... 😭

**Comment by t29mato** [comment]
@lfoppiano I've updated the readme. please check it out

**Comment by lfoppiano** [comment]
I mistakely merged by mistake. After merging I realised that I could not get it to work. I tested with the branch https://github.com/lfoppiano/structure-vision/pull/4 but when clicking I did not have the same behaviour. I tried with both Brave and Firefox.

**Comment by lfoppiano** [comment]
Nevermind, it's working. I've reverted my mess and created version `0.0.20-dev0`

**Pull request merged**
