### PR TITLE
Render selected PDF pages only

### PR DESCRIPTION
**Pull request by t29mato**
## Original Issue

https://github.com/lfoppiano/streamlit-pdf-viewer/issues/22

## Test case

- [x] Annotations are correctly displayed in cases like 'None', '1,3', '2,4', '1,3,5' in multi-page PDFs.

## Test environment

It uses structure-vision
https://github.com/lfoppiano/structure-vision/pull/1

### CODE REVIEW

**Comment by lfoppiano** [comment]
The related issue is #22 isn't it?

**Comment by t29mato** [comment]
> The related issue is #22 isn't it?

Thank you for letting me know.
Yes, it's supposed to be #22
I've updated it.

**Comment by lfoppiano** [comment]
Here the visualised PDF is only the selection. How about scrolling down to the selected page?

**Review by lfoppiano — CHANGES_REQUESTED** [review]
Could you add the related documentation in the readme.md?

**Comment by t29mato** [comment]
> Could you add the related documentation in the readme.md?

I've updated it.

**Review by lfoppiano — APPROVED** [review]

**Pull request merged**
