### PR TITLE
Fix canvas and rendering problems 

### LINKED ISSUE #54: Invalid canvas size
Using [this PDF](https://github.com/user-attachments/files/16319000/solvency2-factsheet.pdf) in [here](https://pdfworkdesk.streamlit.app/) lead to "invalid canvas size" popup.

### PR DESCRIPTION
**Pull request by lfoppiano**
This PR should fix #54, #53 and #56 

The cause of these issues that happens with tabs and expanders comes from our attempt to get the dimension of the space around the PDF, when the width / height are not specified. In addition to a few bugs 😄 

In the case of tabs or expanders, if the PDF is not visible, the width and height of the outer item are 0. From now on, the user has to specify the width or height in such cases. 

Finally, with version <= 0.0.14 when width was not specified, the component tried to use all the available space. Now, if the width is not specified, but the height it is, the PDF will be shown in proportion.

### CODE REVIEW

**Comment by hamdi3** [comment]
Thanks for the update and the new version :)
After testing it myself i came across the following:

- The width of the pdf viewer is automatically set to view at least the full page, meaning you can't increase in a way it would zoom in showing half a page in full width (This was possible before).
- Setting `render_text` to true would cause the following error `m.renderTextLayer is not a function`.
- On the bright side it works with tabs now :)

**Comment by lfoppiano** [comment]
>     * The width of the pdf viewer is automatically set to view at least the full page, meaning you can't increase in a way it would zoom in showing half a page in full width (This was possible before).

Is this behaviour in the tab that is visilble or in the tab that is not visible? could you share the parameters you call the pdf_viewer?

**Comment by hamdi3** [comment]
This behaviour  was seen inside and outside of tabs (the visible ones)
As a browser I'm using `Chrome Version 126.0.6478.183`
I'm calling the code as follows
```
paths = glob("../../*/*.pdf")
for tab,path in zip(streamlit.tabs(paths),paths):
    with tab:
        pdf_viewer(path ,width=1000, height=600) # This was a test to see if changing the width would do anything
```
Hope this helps and lemme know if you need any further details :)

**Comment by hamdi3** [comment]
First of all thanks for the new version :)
Unfortunately not specifying a height or width caused all pages to render at the same time (Removing any scrolling) and would cause the pdf to only render in a single tab (our main issue). One way to go around the issue is to define a container with a height and to only specify the width of the pdf, since defining the height would cause the issue from my previous comment. This is how I manged to do it
```
            paths = glob("../../*/*.pdf")
            for tab,path in zip(streamlit.tabs(paths),paths):
                with tab:
                    with streamlit.container(height=600):
                        pdf_viewer(path, width=800)
```
While I can't share the PDF i have tried to install an older version and the text_render worked with it, so i'm assuming it's not the pdf.

Thanks in advance for your efforts!

**Comment by lfoppiano** [comment]
Yes, I need to solve the bug of the renderText and then iterate once more on the other problem. Thanks for your feedback.

**Comment by lfoppiano** [comment]
@hamdi3 I checked again and I should have fixed the problem with the `renderText=True`. Somehow it was related to a [change in a recent pdf.js version](https://github.com/mozilla/pdf.js/issues/18206). 

You can check version `0.0.16-dev1` which is being built.

For the other behaviour, I'm not sure what's the best approch.

**Pull request merged**
